### PR TITLE
Remove STAGING Environment from SDK

### PR DESCRIPTION
**Pull request by sshropshire**
### Summary of changes

 - Let's remove the `STAGING` environment from the SDK 

 ### Checklist

 - [x] Added a changelog entry

- @sshropshire

### CODE REVIEW

**Comment by emartynov** [comment]
Interesting, wasn't some of these changes already done in #171 ?

Ah oke, that PR was never landed. Sorry for the noise.

**Comment by sshropshire** [comment]
> Interesting, wasn't some of these changes already done in #171 ?

Yes that is interesting. I'm not entirely sure why we didn't merge that work in.

**Comment by scannillo** [comment]
👍 Looks like we have some remnants in the [`PayPalDataCollectorEnvironment`](https://github.com/paypal/paypal-android/blob/957231c5dcca6d20c237e3c44e5f66b2f80c13b1/FraudProtection/src/main/java/com/paypal/android/fraudprotection/PayPalDataCollectorEnvironment.kt#L14) + tests

**Comment by sshropshire** [comment]
> 👍 Looks like we have some remnants in the [`PayPalDataCollectorEnvironment`](https://github.com/paypal/paypal-android/blob/957231c5dcca6d20c237e3c44e5f66b2f80c13b1/FraudProtection/src/main/java/com/paypal/android/fraudprotection/PayPalDataCollectorEnvironment.kt#L14) + tests

Yup! That'll be removed in an upcoming PR. We shouldn't need that enum for data collector.

**Review by scannillo — APPROVED** [review]

**Review by jaxdesmarais — APPROVED** [review]
👻

**Pull request merged**
