### PR TITLE
Rename: PayPalNativeCheckout prefix for Native checkout integration

### PR DESCRIPTION
**Pull request by jcnoriega**
Thank you for your contribution to PayPal. 

> Before submitting this PR, note that we cannot accept language translation PRs. We have a dedicated localization team to provide the translations. If there is an error in a specific translation, you may open an issue and we will escalate it to the localization team.

### Summary of changes

 - Refactor to rename all of the classes to start with the prefix `PayPalNativeCheckout`

 ### Checklist

 - [ ] Added a changelog entry

- @jcnoriega

### CODE REVIEW

**Review by sshropshire — APPROVED** [review]
🌊

**Comment by sshropshire** [comment]
q: Does this need to happen on iOS too?

**Comment by jcnoriega** [comment]
@sshropshire this is to align Android to iOS actually

**Comment by sshropshire** [comment]
@jcnoriega ah 👍

**Pull request merged**
